### ISSUE TITLE
Индикатор поворота руля

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [vsulako/AFFBWheelGUI#1]
Привет. Можно добавить индикатор поворота рулевого колеса в программу, типа как у Logitech или другое? Было бы удобнее калибровать руль. 

![image](https://user-images.githubusercontent.com/31993282/169840917-fa29add8-3cd9-44a8-ac02-981118fe9242.png)

**Comment by vsulako** [comment]
думаю, можно. Попробую.

**Comment by vsulako** [comment]
Вот такой.
![vi](https://user-images.githubusercontent.com/95934592/169875356-7546135c-b27b-44c5-abc8-1f93af3d4441.png)

**Comment by lazenyuk-dmitry** [comment]
Отлично) спасибо. Будет удобнее руль крутить и смотреть результаты.
