### ISSUE TITLE
'Output disabled' axes noise in GUI

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [vsulako/AFFBWheelGUI#2]
Когда ставишь галочку 'Output disabled' то ось глушится как и нужно это видно в панели управления Windows. Но в GUI оси по прежнему шумят. Можно ли когда стоит галочка 'Output disabled' не показывать шумы в GUI?

**Comment by lazenyuk-dmitry** [comment]
И еще в окне есть внутренний скрол когда оно не на весь экран. Так вот он не скролится колесиком мышки а было бы удобно. Не критично но было бы удобнее.

**Comment by vsulako** [comment]
Сделал.

**Comment by lazenyuk-dmitry** [comment]
все отлично. Проверил.
