### ISSUE TITLE
Настройка угла поворота руля

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [vsulako/AFFBWheelGUI#3]
@vsulako, а можно ли сделать так чтобы в инпут `Range` можно было вводить вообще любое желаемое значение?

![image](https://user-images.githubusercontent.com/31993282/182182957-c5649d9c-8600-47b8-8be9-e325bfb02fe5.png)

И ты можешь добавить в список `540` градусов для ралли ))

Было бы идеально если был бы селектор как сейчас и еще можно было бы вписать любое значение числовое или был какой то плюсик рядом и можно в список добавить свои значения.

**Comment by vsulako** [comment]
Можно. Сделал ввод любого значения и добавил в список 540. Для собственного списка это придется еще какой-нибудь файл настроек заводить...может потом.

**Comment by lazenyuk-dmitry** [comment]
@vsulako, спасибо. Завтра проверю и закрою issues.

 Можно сделать добавление тогда и что то типо профилей. Чтобы можно было несколько создать и переключаться. Если это кому то нужно будет. Мне и так живётся нормально, мне не нужно) вроде EMC Lite умеет несколько профилей сохранять. И она вроде уже идёт с установщиком.

**Comment by lazenyuk-dmitry** [comment]
Все отлично. Спасибо.
