### ISSUE TITLE
Улучшение документации.

### ISSUE THREAD

**Issue by lazenyuk-dmitry** [vsulako/AFFBWheelGUI#4]
@vsulako привет. Я тут хочу документацию написать для GUI. И у меня есть вопросы. 

Что такое Trim у осей?

**Comment by vsulako** [comment]
См. описание команд для компорта.

> axistrim <axis>
> axistrim <axis> <trimlevel>
> Показать/установить значение округления для аналоговой оси.
> Побитово уменьшает разрешение исходных (raw) показаний оси для борьбы с нежелательным шумом. Например, при установке значения 3 показания будут меняться с шагом 8 (2 в степени 3).
> Если на оси присутствует шум, можно попробовать увеличить это значение (однако, все же лучше найти причину шума а не скрывать его таким образом)

**Comment by lazenyuk-dmitry** [comment]
Я тут накидал немного. Пока только на русском. Можете посмотреть почитать, может быть что то поправить в моем описании. 

https://github.com/lazenyuk-dmitry/AFFBWheelGUI/blob/feature/improved-readme/README_RU.md

ветка feature/improved-readme.

Я вот не найду ничего про `Inertial gain`, понятно что это инерция) Но примера никакого нету.

Ну и там может еще какие эффекты можно получше описать.

**Comment by vsulako** [comment]
Has center описано дважды, 

Про эффекты, мне кажется, написано избыточно много.
Можно написать что это коэффициенты усиления для каждого из эффектов ОС DirectX.
Ramp - усилие изменяется с одного уровня до другого.
Square, Sine, Triangle, Sawtooth - усилие изменяется по периодической зависимости от времени (прямоугольный/треугольный/пилообразный сигнал/синусоида), может применяться для создания вибрации.
Spring - усилие зависит от положения руля, применяется для имитации силы возвращающей руль к центру.
Damper - усилие зависит от угловой скорости, применяется для имитации сопротивления руля вращению (нагруженности).
Inertia - усилие зависит от углового ускорения, должно имитировать сопротивление изменению скорости вращения (инерцию). 
Friction - создает постоянное усилие, сопротивляющееся вращению (аналогично Damper, но чуть иначе) Тоже должно имитировать нагруженность.
На практике в играх зачастую применяется только эффект Constant, иногда еще Spring и Damper. Остальные едва ли можно встретить.
Лучше не трогать эти настройки а силу ОС регулировать в игре, если есть такая  возможность.
