### ISSUE TITLE
Integration of Keyboard Hotkey for Rotary Encoder Centering in GUI App

### ISSUE THREAD

**Issue by 5nax** [vsulako/AFFBWheelGUI#7]
**Description**
I'm currently using a basic rotary encoder ([Himalayan Solution Rotary Encoder](https://himalayansolution.com/product/rotary-encoder-big)) for gaming purposes. Living in a region with limited access to major online retailers like Amazon, this was the most viable option available to me. The encoder functions well for my needs, but there's a specific enhancement that could significantly improve its usability in gaming.

Problem
While gaming, I frequently need to re-center the wheel of the rotary encoder. Currently, this requires me to pause or exit the game, which is disruptive and inconvenient.

Proposed Solution
I propose the addition of a feature to the GUI application that accompanies the rotary encoder: the ability to assign a keyboard hotkey. This hotkey would allow users to re-center the wheel without needing to leave or pause the game.

**Comment by vsulako** [comment]
I think such hotkey can be added.
But you can assign one wheel's button to do centering. It will work anytime, even without GUI running. Or you don't have any buttons on wheel?

**Comment by 5nax** [comment]
I use a NodeMCU to setup a button box, H-Shifter and a Handbrake. I am only using the pro micro for the wheel, FFB and the pedals. I've managed to modify the code a bit to change the pin no 8 to act as a regular button and center the wheel using the button; Which was failry simple to do. Adding a Hotkey would cerrtainly be beneficial for people without alot of knowlege of coding but yeah thank you anyways.
